services:
  db:
    image: postgres:16
    container_name: spotify_insights_db
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: spotify
      POSTGRES_PASSWORD: spotify
      POSTGRES_DB: spotify_insights
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
